---

- name: Set default managed_files to empty list
  set_fact:
    managed_files: []

- name: "Configure consul services"
  template:
    dest: "{{ consul_configd_dir }}/{{ item.name }}.json"
    src: service.json.j2
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  with_items: "{{ consul_services }}"
  notify:
  - restart consul

- name: Get list of service config files
  find:
    paths: "{{ consul_configd_dir }}"
    patterns: '*.json'
    file_type: file
  register: services_enabled

- name: Set var for enabled services
  set_fact:
    services_enabled_files: "{{ services_enabled['files'] }}"

- name: Set fact with list of existing configuration files
  set_fact:
    list_current_service_config: "{{ list_current_service_config |default([]) + [ item.path ] }}"
  with_items: "{{ services_enabled_files }}"

- name: Set fact with list of service we manage
  set_fact:
    managed_files: "{{ managed_files |default([]) }} + \
    [ '{{ consul_configd_dir }}/{{ item.name }}.json' ]"
  with_items: "{{ consul_services }}"

- name: Delete non declared services
  file:
    path: "{{ item }}"
    state: absent
  when:
  - list_current_service_config is defined
  - item not in managed_files
  with_items: "{{ list_current_service_config }}"
  notify:
  - restart consul
