---

# apt
upgrade_packages: no

# node_exporter
node_exporter_web_listen_address: "{{ ip }}:9100"

# blackbox
blackbox_exporter_web_listen_address: "{{ ip }}:9115"

# victoriametrics
victoria_listen_ip: "{{ ip }}"
victoria_listen_port: "8428"

# alertmanager
alertmanager_web_listen_address: "{{ ip }}:9093"

# prometheus
prometheus_web_listen_address: "{{ ip }}:9090"
prometheus_remote_write_url: http://{{ hostvars[groups['victoriametrics'][0]].ip }}:{{ victoria_listen_port }}/api/v1/write

# consul
consul_bind_address: '{{ ip }}'
consul_client_address: "{{ ip }}"
consul_datacenter: 'vag1'
consul_connect:
  enabled: true
consul_servers: "{{ groups['consul'] | map('extract', hostvars, ['ip']) | list }}"
consul_raw_key: "{{ lookup('env','CONSUL_KEY') }}"
consul_services:
- name: "node_exporter"
  tags: ['prometheus']
  address: "{{ ip }}"
  port: "9100"
  meta:
    exporter: node_exporter
