---

- name: Copy the node_exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
  - Reload systemd daemon
  - Restart node_exporter systemd service

- name: Ensure node_exporter systemd service is enabled and started
  become: true
  systemd:
    name: node_exporter
    state: started
    enabled: true
