---

- name: Ensure {{ victoria_group }} group
  group:
    name: "{{ victoria_group }}"
    system: yes
    state: present

- name: Ensure {{ victoria_user }} user
  user:
    name: "{{ victoria_user }}"
    group: "{{ victoria_group }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no

- name: Ensure stack directories exists
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ victoria_user }}"
    group: "{{ victoria_group }}"
    mode: '755'
  with_items:
  - "{{ victoria_config_dir }}"
  - "{{ victoria_storage_dir }}"

- name: Copy docker-compose
  template:
    src: "docker/docker-compose.yml.j2"
    dest: "{{ victoria_config_dir }}/docker-compose.yml"
    owner: "{{ victoria_user }}"
    group: "{{ victoria_group }}"
    mode: '644'

- name: Start containers
  command: docker-compose -f "{{ victoria_config_dir }}/docker-compose.yml" up -d --force-recreate
