---

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart node_exporter systemd service
  systemd:
    name: node_exporter
    state: restarted

- name: Restart node_exporter service
  service:
    name: node_exporter
    state: restarted
