---

- name: Copy the blackbox_exporter init.d / upstart service file
  template:
    src: blackbox_exporter.conf.j2
    dest: /etc/init/blackbox_exporter.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure blackbox_exporter is (re)started
  become: true
  service:
    name: blackbox_exporter
    state: restarted
